# azure-cd-pipeline.yml

trigger: none

resources:
  pipelines:
    - pipeline: ci_pipeline
      source: CI - Test     # ✅ Doit correspondre exactement au nom visible dans Azure
      trigger:
        branches:
          include:
            - master

stages:
  - stage: Deploy
    displayName: 'Déploiement vers Azure App Service'
    jobs:
      - deployment: DeployToAppService
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'specific'
                    project: $(System.TeamProject)
                    pipeline: ci_pipeline
                    artifactName: 'drop'
                    targetPath: '$(Pipeline.Workspace)/drop'

                - script: |
                    echo "Contenu de drop/"
                    ls -la $(Pipeline.Workspace)/drop
                  displayName: 'Lister les fichiers téléchargés'

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'AzureConnection'
                    appName: 'mlp-inference-api'
                    package: '$(Pipeline.Workspace)/drop'
                    startupCommand: 'startup.sh'
