# azure-pipelines-devOps.yml

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndTest
    displayName: 'CI - Build, Test, and Publish'
    steps:

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install dependencies'

      - script: |
          echo "Running tests..."
          pytest tests/
        displayName: 'Run tests'

      - script: |
          mkdir -p drop
          cp api.py requirements.txt startup.sh mlp.py drop/
        displayName: 'Préparer les fichiers à déployer'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'drop'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        displayName: 'Publier l’artefact pour le CD'
