# azure-pipelines-cd.yml

trigger: none

resources:
  pipelines:
    - pipeline: ci_pipeline                # alias local pour la ressource pipeline
      source: CI - Test                    # ⚠️ NOM EXACT du pipeline CI (visible dans l'interface Azure)
      trigger:
        branches:
          include:
            - master

stages:
  - stage: Deploy
    displayName: 'Déploiement vers Azure App Service'
    jobs:
      - deployment: DeployToAppService
        displayName: 'Déployer sur App Service'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'specific'
                    project: $(System.TeamProject)
                    pipeline: CI - Test                # ⚠️ nom du pipeline, PAS l'alias ci_pipeline
                    artifactName: 'drop'
                    targetPath: '$(Pipeline.Workspace)/drop'

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'AzureConnection'         # nom du service connection Azure
                    appName: 'mlp-inference-api'                 # nom de ton App Service
                    package: '$(Pipeline.Workspace)/drop'        # dossier contenant les fichiers déployés
