# azure-pipelines-devOps.yml

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pytest tests/
    displayName: 'Run tests'

  - script: |
      mkdir -p drop
      cp api.py drop/
      cp mlp.py drop/
      cp requirements.txt drop/
      cp startup.sh drop/
      chmod +x drop/startup.sh
      zip -r drop.zip drop/
    displayName: 'Préparer et zipper le dossier drop'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'drop.zip'          # publie le zip
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publier le zip pour le CD'
