# azure-cd-pipeline.yml

trigger: none

resources:
  pipelines:
    - pipeline: ci_pipeline                # nom interne utilisé dans ce fichier
      source: CI_Test                     # nom exact de la pipeline CI (sans guillemets si pas d’espace)
      trigger:
        branches:
          include:
            - master

stages:
  - stage: Deploy
    jobs:
      - deployment: DeployToAppService
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'specific'
                    project: $(System.TeamProject)
                    pipeline: $(resources.pipeline.ci_pipeline.pipelineID)
                    artifactName: 'drop'
                    targetPath: '$(Pipeline.Workspace)/drop'

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'AzureConnection'
                    appName: 'mlp-inference-api'
                    package: '$(Pipeline.Workspace)/drop'
                    startUpCommand: 'bash startup.sh'
