# azure-cd-pipeline.yml
trigger: none

resources:
  pipelines:
    - pipeline: ci_pipeline
      source: Angelhuu.mlp-inference-api
      trigger:
        branches:
          include:
            - master

stages:
  - stage: Deploy
    jobs:
      - deployment: DeployToAppService
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'specific'
                    project: $(System.TeamProject)
                    pipeline: ci_pipeline
                    runVersion: 'latest'
                    artifactName: 'drop'
                    targetPath: '$(Pipeline.Workspace)/drop'
                  displayName: 'Télécharger l’artefact depuis la CI'

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'AzureConnection'
                    appName: 'mlp-inference-api'
                    package: '$(Pipeline.Workspace)/drop'
                  displayName: 'Déployer sur Azure App Service'
