# azure-cd-pipeline.yml
name: CD - Deploy MLP Inference API
trigger: none

resources:
  pipelines:
    - pipeline: ci_pipeline  # Nom local
      source: Angelhuu.mlp-inference-api  # Nom exact de ta pipeline CI dans Azure DevOps
      trigger:
        branches:
          include:
            - master

stages:
  - stage: Deploy
    displayName: 'Déploiement Azure App Service'
    jobs:
      - deployment: DeployToAppService
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: ci_pipeline
                  artifact: drop

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'AzureConnection'
                    appName: 'mlp-inference-api'
                    package: '$(Pipeline.Workspace)/drop'
