trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pytest tests/
    displayName: 'Run tests'

  - script: |
      mkdir -p drop
      cp api.py requirements.txt startup.sh mlp.py host.json drop/
    displayName: "Préparer les fichiers à déployer"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'drop'
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: "Publier l’artefact pour le CD"
