# azure-pipelines-devOps.yml
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pytest tests/
    displayName: 'Run tests'

  # Étape 1 : créer un dossier drop et y copier ce qu'on veut déployer
  - script: |
      mkdir -p drop
      cp app.py drop/
      cp -r ml_models/ drop/              # adapte selon ton projet
      cp requirements.txt drop/
    displayName: 'Préparer les fichiers à déployer'

  # Étape 2 : publier ce dossier comme artefact nommé 'drop'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'drop'
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publier l’artefact pour le CD'
