# azure-cd-pipeline.yml

trigger: none

resources:
  pipelines:
    - pipeline: ci_pipeline              # identifiant interne
      source: CI - Test                  # 🔁 NOM EXACT de ta pipeline CI dans l’interface DevOps
      trigger:
        branches:
          include:
            - master

stages:
  - stage: Deploy
    jobs:
      - deployment: DeployToAppService
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'specific'
                    project: $(System.TeamProject)
                    pipeline: ci_pipeline
                    artifactName: 'drop'
                    targetPath: '$(Pipeline.Workspace)/drop'

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'AzureConnection'
                    appName: 'mlp-inference-api'
                    package: '$(Pipeline.Workspace)/drop/drop.zip'
