trigger: none  # Pas automatique, déclenche manuellement ou via pipeline CI

pool:
  vmImage: ubuntu-latest

variables:
  terraformWorkingDirectory: 'infra'

stages:
- stage: Terraform_Apply
  jobs:
  - job: Terraform
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.7.0'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(terraformWorkingDirectory)

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(terraformWorkingDirectory)
        environmentServiceNameAzureRM: 'AZURE-SERVICE-CONNECTION'
        args: '-auto-approve'
